"""PDF Report Generator using reportlab (full Unicode support)."""
from datetime import datetime

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    import io
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

# Keep backward compat alias
FPDF_AVAILABLE = REPORTLAB_AVAILABLE


def generate_pdf_report(income: float, age: float, experience: float,
                         prob: float, decision: str, confidence: str,
                         ci_lower: float, ci_upper: float,
                         explanation: str, adverse_notice: dict | None = None) -> bytes | None:
    if not REPORTLAB_AVAILABLE:
        return None

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                             rightMargin=2*cm, leftMargin=2*cm,
                             topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle("title", parent=styles["Title"],
                                  textColor=colors.white,
                                  backColor=colors.HexColor("#1f77b4"),
                                  alignment=TA_CENTER, fontSize=18, spaceAfter=12)
    story.append(Paragraph("CrediSense AI - Loan Risk Assessment Report", title_style))
    story.append(Spacer(1, 0.3*cm))

    # Metadata
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    story.append(Paragraph("Model: LightGBM | Dataset: Kaggle Loan Prediction (252k records)", styles["Normal"]))
    story.append(Spacer(1, 0.4*cm))

    # Decision banner
    dec_color = {"Approve": "#d4edda", "Manual Review": "#fff3cd"}.get(decision, "#f8d7da")
    dec_style = ParagraphStyle("dec", parent=styles["Heading2"],
                                backColor=colors.HexColor(dec_color),
                                alignment=TA_CENTER, spaceAfter=8)
    story.append(Paragraph(f"Decision: {decision} | Risk: {prob:.1%} | Confidence: {confidence}", dec_style))
    story.append(Spacer(1, 0.3*cm))

    # Inputs table
    story.append(Paragraph("Applicant Inputs (Normalized)", styles["Heading3"]))
    input_data = [["Income", "Age", "Experience"],
                  [f"{income:.3f}", f"{age:.3f}", f"{experience:.3f}"]]
    t = Table(input_data, colWidths=[5*cm, 5*cm, 5*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1f77b4")),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
        ("ALIGN",      (0,0), (-1,-1), "CENTER"),
        ("GRID",       (0,0), (-1,-1), 0.5, colors.grey),
        ("FONTSIZE",   (0,0), (-1,-1), 11),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.4*cm))

    # Risk metrics
    story.append(Paragraph("Risk Assessment", styles["Heading3"]))
    metrics = [
        ["Metric", "Value"],
        ["Default Probability", f"{prob:.2%}"],
        ["Safe Probability",    f"{1-prob:.2%}"],
        ["95% Confidence Interval", f"[{ci_lower:.2%}, {ci_upper:.2%}]"],
        ["Confidence Level",    confidence],
    ]
    mt = Table(metrics, colWidths=[9*cm, 7*cm])
    mt.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1f77b4")),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.whitesmoke, colors.white]),
        ("GRID",       (0,0), (-1,-1), 0.5, colors.grey),
        ("FONTSIZE",   (0,0), (-1,-1), 11),
    ]))
    story.append(mt)
    story.append(Spacer(1, 0.4*cm))

    # Explanation
    story.append(Paragraph("Explanation", styles["Heading3"]))
    story.append(Paragraph(explanation, styles["Normal"]))
    story.append(Spacer(1, 0.4*cm))

    # Adverse action
    if adverse_notice and adverse_notice.get("required"):
        adv_style = ParagraphStyle("adv", parent=styles["Heading3"],
                                    backColor=colors.HexColor("#f8d7da"))
        story.append(Paragraph("Adverse Action Notice", adv_style))
        notice_text = adverse_notice["notice"].replace("\n", "<br/>")
        story.append(Paragraph(notice_text, styles["Normal"]))
        story.append(Spacer(1, 0.2*cm))
        story.append(Paragraph(adverse_notice["citation"], styles["Italic"]))
        story.append(Spacer(1, 0.4*cm))

    # Footer
    footer_style = ParagraphStyle("footer", parent=styles["Normal"],
                                   fontSize=8, textColor=colors.grey, alignment=TA_CENTER)
    story.append(Paragraph(
        "This report is generated by an AI model and should be reviewed by a qualified analyst.",
        footer_style))
    story.append(Paragraph(
        "Sources: Kaggle | scikit-learn | LightGBM (NeurIPS 2017) | World Bank Open Data",
        footer_style))

    doc.build(story)
    return buf.getvalue()
