"""PDF Report Generator using fpdf2."""
from pathlib import Path
from datetime import datetime
import io

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


def generate_pdf_report(income: float, age: float, experience: float,
                         prob: float, decision: str, confidence: str,
                         ci_lower: float, ci_upper: float,
                         explanation: str, adverse_notice: dict | None = None) -> bytes | None:
    """Generate a PDF report for a single prediction. Returns bytes or None if fpdf unavailable."""
    if not FPDF_AVAILABLE:
        return None

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_fill_color(31, 119, 180)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 12, "CrediSense AI - Loan Risk Assessment Report", fill=True, ln=True, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Metadata
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(0, 6, f"Model: LightGBM | Dataset: Kaggle Loan Prediction (252k records)", ln=True)
    pdf.ln(4)

    # Decision banner
    pdf.set_font("Helvetica", "B", 14)
    if decision == "Approve":
        pdf.set_fill_color(212, 237, 218)
    elif decision == "Manual Review":
        pdf.set_fill_color(255, 243, 205)
    else:
        pdf.set_fill_color(248, 215, 218)
    pdf.cell(0, 10, f"Decision: {decision}  |  Risk: {prob:.1%}  |  Confidence: {confidence}",
             fill=True, ln=True, align="C")
    pdf.ln(4)

    # Inputs
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Applicant Inputs (Normalized)", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(60, 7, f"Income: {income:.3f}", border=1)
    pdf.cell(60, 7, f"Age: {age:.3f}", border=1)
    pdf.cell(60, 7, f"Experience: {experience:.3f}", border=1, ln=True)
    pdf.ln(4)

    # Risk metrics
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Risk Assessment", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Default Probability: {prob:.2%}", ln=True)
    pdf.cell(0, 7, f"Safe Probability: {1-prob:.2%}", ln=True)
    pdf.cell(0, 7, f"95% Confidence Interval: [{ci_lower:.2%}, {ci_upper:.2%}]", ln=True)
    pdf.cell(0, 7, f"Confidence Level: {confidence}", ln=True)
    pdf.ln(4)

    # Explanation
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Explanation", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, explanation)
    pdf.ln(4)

    # Adverse action notice
    if adverse_notice and adverse_notice.get("required"):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_fill_color(248, 215, 218)
        pdf.cell(0, 8, "Adverse Action Notice", fill=True, ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, adverse_notice["notice"])
        pdf.ln(2)
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, adverse_notice["citation"], ln=True)
        pdf.ln(4)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 6, "This report is generated by an AI model and should be reviewed by a qualified analyst.",
             ln=True, align="C")
    pdf.cell(0, 6, "Sources: Kaggle | scikit-learn | LightGBM (NeurIPS 2017) | World Bank Open Data",
             ln=True, align="C")

    return bytes(pdf.output())
